services:
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8081:8081"
    networks:
      - momo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80" 
    networks:
      - momo-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          memory: 128M
networks:
  momo-network:
    driver: bridge